### ISSUE TITLE
Raspberry Pi - Lost connection with Node Red

### ISSUE THREAD

**Issue by YatinHK** [ibm-watson-iot/node-red-contrib-ibm-watson-iot#4]
Could you please provide your advise on attached error.
I am unable to connect Node-Red application into Raspberry Pi 3. 

Reuse an iot credential config node for both a Device and Gateway pair of nodes.

That logs shows a fatal uncaught error with the watson iot node:
 
[red] Uncaught Exception:
10 May 12:02:04 - TypeError: Object #<DeviceClient> has no method 'subscribeToDeviceCommand'
at Object.callback (/usr/lib/node_modules/node-red-contrib-ibm-watson-iot/application/wiotp.js:171:24)
at DeviceClient.<anonymous> (/usr/lib/node_modules/node-red-contrib-ibm-watson-iot/application/wiotp.js:48:42)
at DeviceClient.emit (events.js:92:17)
at MqttClient.<anonymous> (/usr/lib/node_modules/node-red-contrib-ibm-watson-iot/node_modules/ibmiotf/dist/clients/DeviceClient.js:104:19)
at MqttClient.emit (events.js:117:20)
at MqttClient._handleConnack (/usr/lib/node_modules/node-red-contrib-ibm-watson-iot/node_modules/mqtt/lib/client.js:670:10)
at MqttClient._handlePacket (/usr/lib/node_modules/node-red-contrib-ibm-watson-iot/node_modules/mqtt/lib/client.js:274:12)
at process (/usr/lib/node_modules/node-red-contrib-ibm-watson

Please provide your valuable support on my issue.
Waiting for reply, 
Yatin Kamble
yatin.kamble@in.ibm.com
[NodeReD-Failed.docx](https://github.com/ibm-watson-iot/node-red-contrib-ibm-watson-iot/files/989743/NodeReD-Failed.docx)
[Lost Connection.docx](https://github.com/ibm-watson-iot/node-red-contrib-ibm-watson-iot/files/989744/Lost.Connection.docx)

**Comment by amprasanna** [comment]
Closing this issue, as the User acknowledged that he was experiencing the issue while using incorrect connection details
